In [ ]:
#question 1
import numpy as np
import random
import matplotlib.pyplot as plt
roll_no = np.array([1,2,3,4,5,6,7,8,9,10])
marks = np.array([78, 85, 90, 67, 88, 76, 92, 81, 69, 74])
attendance = np.array([90, 85, 95, 80, 88, 92, 96, 89, 84, 86])
gender = np.array(['M','F',None,'M','F',None,'M','F','M',None])

null_count = np.sum(gender == None)
print(null_count)

print(np.mean(marks))

m_count = np.sum(gender == 'M')
print(m_count)

f_count = np.sum(gender == 'F')
print(f_count)

plt.figure()
plt.bar(['Male', 'Female'], [m_count, f_count])
plt.xlabel("Gender")
plt.ylabel("Number of Students")
plt.title("Gender-wise Distribution of Students")
plt.legend(["Students Count"])
plt.show()

plt.figure()
plt.hist(marks, bins=5)
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.title("Distribution of Students' Marks")
plt.legend(["Marks Frequency"])
plt.show()

In [ ]:
#QUESTION 2 
import random
l=[]
for i in range:
    l.append(random.randint(0,101)
print(l)

In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\naksh\\Desktop\\AI ML\\medical_records.csv")
df2=pd.read_csv("C:\\Users\\naksh\\Desktop\\AI ML\\patient_details.csv")
#info , head ,tail , describe,size,ndim
df.head()

  record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0      R101       P013  Hypertension  120/80        140.0        2000
1      R102       P105      Diabetes  120/80          NaN        2500
2      R103       P098  Hypertension    high        140.0        3000
3      R104       P038        Asthma  140/90          NaN        3000
4      R105       P040        Asthma  130/85          NaN        1500

In [2]:
df.tail()

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

In [3]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   record_id    120 non-null    object
 1   patient_id   120 non-null    object
 2   diagnosis    120 non-null    object
 3   bp           120 non-null    object
 4   sugar_level  85 non-null     float64
 5   visit_cost   120 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.8+ KB

In [4]:
df.describe()

       sugar_level   visit_cost
count    85.000000   120.000000
mean    141.058824  2287.500000
std      27.689758   567.548539
min     110.000000  1500.000000
25%     110.000000  2000.000000
50%     140.000000  2500.000000
75%     180.000000  3000.000000
max     180.000000  3000.000000

In [5]:

df.size

720

In [6]:

df.ndim

2

In [7]:
df.shape

(120, 6)

In [8]:
print(df2.isnull().mean())

patient_id        0.000000
name              0.176923
age               0.184615
gender            0.000000
city              0.000000
admission_date    0.000000
height_cm         0.000000
dtype: float64

In [9]:
df_filled = df.fillna(0,inplace=True)

In [10]:
print(df_filled)

None

In [11]:
print(df)

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80        140.0        2000
1        R102       P105      Diabetes  120/80          0.0        2500
2        R103       P098  Hypertension    high        140.0        3000
3        R104       P038        Asthma  140/90          0.0        3000
4        R105       P040        Asthma  130/85          0.0        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          0.0        1500
117      R218       P063  Hypertension  140/90          0.0        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

[120 rows x 6 columns]

In [13]:
df2['age'] = df2['age'].fillna(df2['age'].mean())

In [14]:
print(df2)

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]